---
id: heiseirb-6
base_name: slide
tags: ['ruby', 'rails']
presentation_date: 
version: 1.0.0
licenses: ['MIT']
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :markdown
  name: unasuke
  email: 
  rubygems_user: unasuke
  slideshare_user: 
  speaker_deck_user: 
